name: Setup test scenario

on:
  workflow_dispatch:

env:
  BRANCH_NAME: "feature-1234567890"
  TEST_BRANCH: "test/main"

jobs:
  create_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branches
        run: |
          git branch | grep -v "main" | xargs git branch -D
          git push origin --delete $(git branch | grep -v "main" | awk '{print $1}')

      - name: Create test branch
        run: |
          git checkout -b ${{ env.TEST_BRANCH }}
          git push origin ${{ env.TEST_BRANCH }}

      - name: Create feature branch
        run: |
          branch_name=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
          $branch_name = "feature-$branch_name"
          git checkout -b $branch_name
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: Create random file
        run: |
          file_name=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
          echo "This is a random file" > $file_name

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.ref }}
          branch: feature-$branch_name
          title: "Pull Request for ${{ github.ref }}"
          body: "This pull request was created by the workflow."
          assignees: ${{ github.actor }}
