name: Setup test scenario

on:
  workflow_dispatch:

env:
  BRANCH_NAME: "feature"
  TEST_BRANCH: "test/main"

jobs:
  create_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test branch
        run: |
          if git show-ref --quiet refs/heads/${{ env.TEST_BRANCH }}; then
            git push --delete origin ${{ env.TEST_BRANCH }}
          fi
          git checkout -b ${{ env.TEST_BRANCH }}
          git push origin ${{ env.TEST_BRANCH }}

      - name: Create feature branch & file
        run: |
          git checkout -b ${{ env.BRANCH_NAME }}
          echo "This is a random file" > newfile.txt

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.ref }}
          branch: ${{ env.BRANCH_NAME }}
          title: "Pull Request for ${{ github.ref }}"
          body: "This pull request was created by the workflow."
          assignees: ${{ github.actor }}
